name: Try CI/CD pipeline for Backend

# Set the trigger conditions
on:
  push: 
    branches:
      - staging # when Main branch have update try run the script
    paths:
      - 'Backend/**' # When Backend have update
    paths_ignore:
      # wait for the really File structure
    pull_request:
      branches:
        - staging # when Main branch has PR trigger

  # Set some manual work,like wait user check for deploy
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to production'
        required: true
        default: 'true' # Default not deploy, wait user check
        type: boolean
      build_docker:
        description: 'Build Docker Image'
        required: true
        default: 'true'
        type: boolean
  

# Set the CI/CD pipeline
jobs:
  # Build Stage
  build:
    runs-on: ubuntu-latest # build environment set as Ubuntu
    outputs:
      docker-image: ${{ steps.build-docker.outputs.image-tag}}

    steps:
      # Checkout Project Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set the project JDK
      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: '17' # set JDK version
          distribution: 'temurin'

      # Cache Mvn project Dependency
      - name: Cache Mvn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build Project
      - name: Build with Mvn
        run: mvn clean install -DskipTests=true
        working-directory: Backend/KebunJio

      # Run test (Junit)
      - name: Run tests with Mvn
        run: mvn test
        working-directory: Backend/KebunJio

      - name: Update test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: Backend/KebunJio/target/surefire-reports/*.xml
      

      # Generate JAR file
      - name: Build JAR
        run: mvn clean package -DskipTests=true
        working-directory: Backend/KebunJio
      
      # If we use Docker
      # Build Docker Iamge
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_NAME }}/kebunjio:${{ github.sha }} .
        working-directory: Backend/KebunJio

      # Login Dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        working-directory: Backend/KebunJio
        with:
          username: ${{ secrets.DOCKERHUB_NAME }} # Write in Github Secrets
          password: ${{ secrets.DOCKERHUB_PASSWORD }} # Write in Github Secrets 

      # Push image to Dockerhub
      - name: Push Docker image
        if: ${{ github.event.inputs.build_docker == 'true' }}
        working-directory: Backend/KebunJio
        run: |
          docker push ${{ secrets.DOCKERHUB_NAME }}/kebunjio:${{ github.sha }}

  # Deploy stage
  deploy:
    runs-on: ubuntu-latest

    needs: build # After build stage finished
    if: ${{ github.event.inputs.deploy == 'true' }}

    steps:
      # Checkout Project Code
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/google_cloud_key
          chmod 600 ~/.ssh/google_cloud_key
          ssh-keyscan -H <your-server-ip> >> ~/.ssh/known_hosts

      # Connect to Target Server
      - name: Connect Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY}} shidubei@34.124.209.141 

      - name: Pull Docker image
        run: |
          ssh -i ~/.ssh/google_cloud_key shidubei@kebunjio-test << 'EOF'
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKERHUB_NAME }}/kebunjio:${{ github.sha }}
            docker stop kebunjio || true && docker rm kebunjio || true
            docker run -d --name kebunjio -p 8080:8080 ${{ secrets.DOCKERHUB_NAME }}/kebunjio:${{ github.sha }}
          EOF


        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
